Задача 1

1. Постройте группировку, по которой видно, какое количество заказов было для
каждой пары «животное — порода» и какой средний чек был по этой паре.
2. Найдите заказы с аномально высокими чеками, например которые превышают среднее значение на 1,5 стандартных отклонения.
3. Найдите медианный чек услуги для каждого животного в каждом возрасте.

In [2]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns
import random
import math

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
path = '/content/drive/MyDrive/животные.xlsx'
an = pd.read_excel(path)
an.head()

   id_order  animal                species  check  age
0   3645743   Кошка                Уличная  35124   13
1   3645744   Кошка  Домашняя обыкновенная  30789   20
2   3645745  Собака                Уличная  30386   12
3   3645745  Собака  Домашняя обыкновенная  33967   18
4   3645746  Собака  Домашняя обыкновенная  57745    8

In [5]:
#Постройте группировку, по которой видно, какое количество заказов было для каждой пары «животное — порода» и какой средний чек был по этой паре
an_gr = an.groupby(['animal','species']).agg(cnt_order = ('check', 'count'), avg_check = ('check', 'mean')).\
reset_index().sort_values('animal')
an_gr

                  animal                species  cnt_order     avg_check
0                  Кошка  Домашняя обыкновенная       1037  26252.648987
1                  Кошка    Домашняя породистая        375  27404.896000
2                  Кошка                Уличная        598  24168.826087
3                 Собака  Домашняя обыкновенная        920  26733.493478
4                 Собака    Домашняя породистая        249  20443.963855
5                 Собака                Уличная        774  25679.635659
6  Экзотическое животное  Экзотическое животное        893  28748.667413

In [6]:
#Найдите заказы с аномально высокими чеками, например которые превышают среднее значение на 1,5 стандартных отклонения.
#Находим среднее значение и стандартное отклонение
mean_check = an['check'].mean()
std_check = an['check'].std()
print(mean_check)
print(std_check)

26245.92447379282
33360.29253944129

In [7]:
# Считаем границу: среднее + 1.5 * стандартное отклонение
limit = mean_check + 1.5 * std_check
limit

np.float64(76286.36328295476)

In [8]:
#Определяем аномально высокие чеки
anomal = an[an['check'] > limit]

In [9]:
#Выводим результаты
print(f"Граница аномальных чеков: {limit}")
print(f"Найдено аномальных заказов: {len(anomal)}")

Граница аномальных чеков: 76286.36328295476
Найдено аномальных заказов: 341

In [10]:
#Найдите медианный чек услуги для каждого животного в каждом возрасте.
an_gr_median = an.groupby(['animal','age']).agg(median_check = ('check','median')).reset_index()
an_gr_median

                   animal  age  median_check
0                   Кошка    1        8020.0
1                   Кошка    2       10676.5
2                   Кошка    3       11421.0
3                   Кошка    4        6843.5
4                   Кошка    5       12376.5
..                    ...  ...           ...
70  Экзотическое животное   21       18312.0
71  Экзотическое животное   22       13489.5
72  Экзотическое животное   23       14230.0
73  Экзотическое животное   24       16555.0
74  Экзотическое животное   25       15801.0

[75 rows x 3 columns]

Задача 2

Используя функцию ttest_ind, проверьте равенство средних двух выборок и решите, отвергаете или принимаете нулевую гипотезу.

1.Какой средний чек выше: по собакам или по кошкам?

2.Какой средний чек выше: по экзотическим животным или по собакам?

3.Какой средний чек выше: по экзотическим животным или по кошкам?

4.Существуют ли сегменты (разбиение по породе), в рамках которых средний чек по кошкам больше, чем по собакам?

5.Какой средний чек выше: по экзотическим животным или по домашним породистым кошкам?

In [11]:
#Создаем новые таблицы отдельно
dog = an[an['animal']=='Собака']
cat = an[an['animal']=='Кошка']
exotic = an[an['animal']=='Экзотическое животное']

In [12]:
#1.Какой средний чек выше: по собакам или по кошкам?
#Находим среднее значение
dog_mean = dog['check'].mean()
cat_mean = cat['check'].mean()
exotic_mean = exotic['check'].mean()
print(f'Среднее значение чека по собакам:{dog_mean}')
print(f'Среднее значение чека по кошкам:{cat_mean}')
print(f'Среднее значение чека по экзотическим животным:{exotic_mean}')

Среднее значение чека по собакам:25507.66803911477
Среднее значение чека по кошкам:25847.65721393035
Среднее значение чека по экзотическим животным:28748.667413213887

In [13]:
#Длинна данных выборки
print(len(dog))
print(len(cat))
print(len(exotic))

1943
2010
893

In [14]:
#Решаем с помощью функции ttest_ind и принимаем решение
s, p = stats.ttest_ind(dog['check'], cat['check'])
print(s)
print(p)

-0.33249372919079573
0.7395341130329705

In [15]:
s, p = stats.ttest_ind(exotic['check'], dog['check'])
print(s)
print(p)

2.6948754260038923
0.007083056950678514

In [16]:
s, p = stats.ttest_ind(exotic['check'], cat['check'])
print(s)
print(p)

1.9001559109007526
0.05751171967285473

Ответ на 1 вопрос. Какой средний чек выше: по собакам или по кошкам?

Кошки (25 847.66) и Собаки (25 507.67) — разница случайная (p = 0.74). Чеки одинаковые.

Ответ на 2 вопрос. Какой средний чек выше: по экзотическим животным или по собакам?

Экзотические (28 748.67) и Собаки (25 507.67) — экзотические животные значимо дороже (p = 0.007). Разница реальна.

Ответ на 3 вопрос. Какой средний чек выше: по экзотическим животным или по кошкам?

Экзотические (28 748.67) и Кошки (25 847.66) — разница не доказана (p = 0.057). Данных мало. Чеки считаем одинаковыми.

Оталось еще два вопроса.

4.Существуют ли сегменты (разбиение по породе), в рамках которых средний чек по кошкам больше, чем по собакам?

5.Какой средний чек выше: по экзотическим животным или по домашним породистым кошкам?

In [22]:
#4.Существуют ли сегменты (разбиение по породе), в рамках которых средний чек по кошкам больше, чем по собакам?
#Создаем таблицы
cat_home = an[(an['animal'] == 'Кошка') & (an['species'] == 'Домашняя обыкновенная')]
cat_ped = an[(an['animal'] == 'Кошка') & (an['species'] == 'Домашняя породистая')]
cat_str = an[(an['animal'] == 'Кошка') & (an['species'] == 'Уличная')]

dog_home = an[(an['animal'] == 'Собака') & (an['species'] == 'Домашняя обыкновенная')]
dog_ped = an[(an['animal'] == 'Собака') & (an['species'] == 'Домашняя породистая')]
dog_str = an[(an['animal'] == 'Собака') & (an['species'] == 'Уличная')]

In [23]:
#Вводим функцию, которая проверит гипотезу:
def mytest(x1, x2, pvalue=0.05):
    print('разница между средними значениями:', x1.mean()-x2.mean())
    s, p = stats.ttest_ind(x1, x2)
    if p<=pvalue:
        print('Гипотеза отвергается, разница стат. значима')
    else:
        print('Гипотеза не отвергается, средние равны')

In [24]:
#Запускаем функцию на проверку кошки и собаки порода домашняя обыкновенная
mytest(cat_home['check'], dog_home['check'])

разница между средними значениями: -480.8444907970297
Гипотеза не отвергается, средние равны

In [25]:
#Запускаем функцию на проверку кошки и собаки порода домашняя породистая
mytest(cat_ped['check'], dog_ped['check'])

разница между средними значениями: 6960.9321445783135
Гипотеза отвергается, разница стат. значима

In [27]:
cat_m = cat_ped['check'].mean()
dog_m = dog_ped['check'].mean()
print(cat_m)
print(dog_m)

27404.896
20443.963855421687

In [26]:
#Запускаем функцию на проверку кошки и собаки порода уличная
mytest(cat_str['check'], dog_str['check'])

разница между средними значениями: -1510.8095719582088
Гипотеза не отвергается, средние равны

Ответ на вопрос Существуют ли сегменты (разбиение по породе), в рамках которых средний чек по кошкам больше, чем по собакам?

У домашней породистой кошки средний чек больше, чем у домашней породистой собаки.

In [29]:
#5.Какой средний чек выше: по экзотическим животным или по домашним породистым кошкам?
cat_m = cat_ped['check'].mean() #средний чек домашней породистой кошки
exotic_m = exotic['check'].mean() #средний чек экзотических животных
print(cat_m)
print(exotic_m)

27404.896
28748.667413213887

In [30]:
s, p = stats.ttest_ind(exotic['check'], cat_ped['check'])
print(s)
print(p)

0.5837843619715073
0.559469393144282

In [31]:
mytest(cat_ped['check'], exotic['check'])

разница между средними значениями: -1343.7714132138863
Гипотеза не отвергается, средние равны

Статистически значимой разницы между средними чеками экзотических животных и домашних породистых кошек не обнаружено (p > 0.05). Их средние чеки можно считать равными