### Задание 1

Импортируйте файл workouts.csv.
<br>
Выведите тип полученного объекта и его первые 10 строк.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
path = '/content/drive/MyDrive/урок 5/workouts.csv'
workouts = pd.read_csv(path)

In [4]:
workouts.head(10)

,workout_id,cost,start_at,status,workout_schedule_type,client_id,client_status,workout_type,trainer_department,trainer_id
0,30793909,NaN,2020-11-13 12:45,success,trial,22034,NaN,general,Sales,10722051
1,31123309,750.0,2020-11-21 13:00,success,regular,22034,new,general,Spartacus,940642
2,31412167,750.0,2020-11-28 13:00,success,regular,22034,new,general,Spartacus,940642
3,31703605,750.0,2020-12-05 13:00,success,regular,22034,active,general,Spartacus,940642
4,26904500,NaN,2020-08-06 18:20,success,trial,88101,NaN,general,Sales,3826530
5,27205345,750.0,2020-08-15 10:00,success,single,88101,new,general,Consultant,10231664
6,27439942,750.0,2020-08-20 19:00,success,regular,88101,new,general,Consultant,10231664
7,27698497,750.0,2020-08-27 19:00,success,regular,88101,new,general,Consultant,10231664
8,27973407,750.0,2020-09-03 19:00,success,regular,88101,active,general,Consultant,10231664
9,28246406,750.0,2020-09-10 19:00,success,regular,88101,active,general,Spartacus,10231664

### Задание 2

Воспроизведите результат следующего SQL-кода

~~~ sql
select   workout_id
       , start_at
       , client_id
from workouts
where  workout_schedule_type = 'trial'
limit 10
~~~

In [5]:
workouts[workouts['workout_schedule_type']=='trial'][['workout_id','start_at','client_id']].head(10)

     workout_id          start_at  client_id
0      30793909  2020-11-13 12:45      22034
4      26904500  2020-08-06 18:20      88101
16     21715697  2020-04-05 16:20      95272
75     24959688  2020-06-19 08:20     123236
144    21762082  2020-04-06 19:40     154553
192    30409642  2020-11-04 08:45     187496
197    28922956  2020-09-28 17:40     222416
217    20678366  2020-03-10 19:00     239823
225    21388086  2020-03-28 14:20     254624
230    28748969  2020-09-23 20:20     307913

### Задание 3

Воспроизведите результат следующего SQL-кода

~~~ sql
select   workout_id
       , trainer_id
from workouts
where  workout_schedule_type in ('trial', 'regular')
  and trainer_department <> 'Sales'
order by trainer_id
limit 5
~~~

In [12]:
#####
workouts[(workouts['workout_schedule_type'].isin(['trial', 'regular'])) & (workouts['trainer_department'] != 'Sales')][['workout_id','trainer_id']].sort_values('trainer_id').head(5)

        workout_id  trainer_id
104557    31684703        1994
104556    31549515        1994
104555    31452923        1994
103992    26146264        1994
103994    26289527        1994

### Задание 4

Воспроизведите результат следующего SQL-кода

~~~ sql
select   *
from workouts
where  trainer_department like '%Spartacus%'
   and workout_schedule_type not in ('trial', 'single')
order by client_id desc
limit 15
~~~

In [7]:
#####
workouts[
         (workouts['trainer_department'].str.contains('Spartacus', na=False))
        &
         (~workouts['workout_schedule_type'].isin(['trial', 'single']))
        ].sort_values('client_id', ascending=False).head(15)

,workout_id,cost,start_at,status,workout_schedule_type,client_id,client_status,workout_type,trainer_department,trainer_id
101829,25401300,750.0,2020-06-29 21:00,success,regular,5498391,active,general,Spartacus,7415097
101827,24995686,750.0,2020-06-19 21:00,success,regular,5498391,active,general,Spartacus,7415097
101826,24699044,750.0,2020-06-12 21:00,success,regular,5498391,active,general,Spartacus,7415097
101825,24505182,750.0,2020-06-08 21:00,success,regular,5498391,active,general,Spartacus,7415097
101833,26334296,750.0,2020-07-22 21:00,success,regular,5498391,active,general,Spartacus,7415097
101832,26062514,750.0,2020-07-15 21:00,success,regular,5498391,active,general,Spartacus,7415097
101831,25909178,750.0,2020-07-12 11:00,success,regular,5498391,active,general,Spartacus,7415097
101828,25104401,750.0,2020-06-22 21:00,success,regular,5498391,active,general,Spartacus,7415097
101813,22372160,750.0,2020-04-20 21:00,success,regular,5498391,new,general,Spartacus,7415097
101814,22560494,750.0,2020-04-24 21:00,success,regular,5498391,new,general,Spartacus,7415097
101815,22872362,750.0,2020-05-01 21:00,success,regular,5498391,active,general,Spartacus,7415097
101834,26454313,750.0,2020-07-26 11:00,success,regular,5498391,active,general,Spartacus,7415097
101842,28603810,750.0,2020-09-20 11:00,success,regular,5498391,active,general,Spartacus,7415097
101845,29311008,750.0,2020-10-07 21:00,success,regular,5498391,active,general,Spartacus,7415097
101846,29588947,750.0,2020-10-14 21:00,success,regular,5498391,active,general,Spartacus,7415097

### Задание 5

Воспроизведите результат следующего SQL-кода

~~~ sql
select   *
from workouts
where  status = 'success'
    or client_status = 'active' and workout_schedule_type = 'regular'
order by trainer_id
limit 5
~~~

In [8]:
#####
workouts[(workouts['status']=='success') | (workouts['client_status'] == 'active') & (workouts['workout_schedule_type']=='regular')].sort_values('trainer_id').head(5)

,workout_id,cost,start_at,status,workout_schedule_type,client_id,client_status,workout_type,trainer_department,trainer_id
31768,28473667,750.0,2020-09-17 16:00,success,single,752264,active,general,Spartacus,1308
104552,31163419,1000.0,2020-11-22 21:00,success,regular,4511817,active,general,Spartacus,1994
104551,31104473,1000.0,2020-11-20 21:00,success,regular,4511817,active,general,Spartacus,1994
104550,30972409,1000.0,2020-11-17 21:00,success,regular,4511817,active,general,Spartacus,1994
104549,30876908,1000.0,2020-11-15 21:00,success,regular,4511817,active,general,Spartacus,1994

### Задание 6

Воспроизведите результат следующего SQL-кода

~~~ sql
select   workout_id
from workouts
where  client_status = 'new'
    and (trainer_department like 'Sales%' or trainer_department like '%Spartacus')
limit 10
~~~

In [13]:
#####
workouts[(workouts['client_status']== 'new')
& ((workouts['trainer_department'].str.startswith('Sales',na=False)) | (workouts['trainer_department'].str.endswith('Spartacus', na=False)))][['workout_id']].head(10)

    workout_id
1     31123309
2     31412167
17    21818687
18    21983629
19    22118778
20    22254387
21    22434984
22    22549746
23    22722010
76    25116753

### Задание 7

Воспроизведите результат следующего SQL-кода с помощью предварительного создания двух масок.

~~~ sql
select   workout_id
from workouts
where  upper(trainer_department) like '%SPARTACUS%'
   and workout_schedule_type is not null
limit 10
~~~

Первая маска - upper(trainer_department) like '%SPARTACUS%'
<br>
Вторая маска - workout_schedule_type is not null

In [10]:
#####
msk_up = workouts['trainer_department'].str.upper().str.contains('SPARTACUS',na=False)
msk_not_null = workouts['workout_schedule_type'].notna()

In [ ]:
################################################################################################################################
################################################################################################################################
################################################################################################################################

In [14]:
workouts[msk_up & msk_not_null][['workout_id']].head(10)

    workout_id
1     31123309
2     31412167
3     31703605
9     28246406
10    28251627
11    28520640
12    28794282
13    29070139
14    29352465
15    31057309